import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import { Box, Stack } from '@mui/system';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry>
          <Stack minHeight="100vh">
            <Header />
            <Box component="main" flexGrow={1}>
              {children}
            </Box>
            <Footer />
          </Stack>
        </ThemeRegistry>
      </body>
    </html>
  );
}
